/*
 * Copyright 2026 Belgian Secure Communications (BSC)
 * Copyright (c) 2026 Element Creations Ltd.
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial.
 * Please see LICENSE files in the repository root for full details.
 * Modified by Belgian Secure Communications for Beam application on 2026-02-09
 */

/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */

@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.DarkHcColorTokens

/**
 * Semantic colors for the high contrast dark Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsHcDark = SemanticColors(
    bgAccentHovered = DarkHcColorTokens.colorYellow600,
    bgAccentPressed = DarkHcColorTokens.colorYellow1000,
    bgAccentRest = DarkHcColorTokens.colorYellow600,
    bgAccentSelected = DarkHcColorTokens.colorAlphaGreen300,
    bgActionPrimaryDisabled = DarkHcColorTokens.colorGray700,
    bgActionPrimaryHovered = DarkHcColorTokens.colorYellow500,
    bgActionPrimaryPressed = DarkHcColorTokens.colorYellow1000,
    bgActionPrimaryRest = DarkHcColorTokens.colorYellow800,
    bgActionSecondaryHovered = DarkHcColorTokens.colorAlphaGray200,
    bgActionSecondaryPressed = DarkHcColorTokens.colorAlphaGray300,
    bgActionSecondaryRest = DarkHcColorTokens.colorThemeBg,
    bgActionTertiaryHovered = DarkHcColorTokens.colorGray300,
    bgActionTertiaryRest = DarkHcColorTokens.colorThemeBg,
    bgActionTertiarySelected = DarkHcColorTokens.colorGray400,
    bgBadgeAccent = DarkHcColorTokens.colorAlphaGreen500,
    bgBadgeDefault = DarkHcColorTokens.colorAlphaGray500,
    bgBadgeInfo = DarkHcColorTokens.colorAlphaBlue500,
    bgCanvasDefault = DarkHcColorTokens.colorThemeBg,
    bgCanvasDefaultLevel1 = DarkHcColorTokens.colorGray300,
    bgCanvasDisabled = DarkHcColorTokens.colorGray200,
    bgCriticalHovered = DarkHcColorTokens.colorRed1000,
    bgCriticalPrimary = DarkHcColorTokens.colorRed900,
    bgCriticalSubtle = DarkHcColorTokens.colorRed200,
    bgCriticalSubtleHovered = DarkHcColorTokens.colorRed300,
    bgDecorative1 = DarkHcColorTokens.colorLime300,
    bgDecorative2 = DarkHcColorTokens.colorCyan300,
    bgDecorative3 = DarkHcColorTokens.colorFuchsia300,
    bgDecorative4 = DarkHcColorTokens.colorPurple300,
    bgDecorative5 = DarkHcColorTokens.colorPink300,
    bgDecorative6 = DarkHcColorTokens.colorOrange300,
    bgInfoSubtle = DarkHcColorTokens.colorBlue200,
    bgSubtlePrimary = DarkHcColorTokens.colorGray400,
    bgSubtleSecondary = DarkHcColorTokens.colorGray200,
    bgSubtleSecondaryLevel0 = DarkHcColorTokens.colorThemeBg,
    bgSubtleTertiary = DarkHcColorTokens.colorYellow200,
    bgSuccessSubtle = DarkHcColorTokens.colorGreen200,
    borderAccentSubtle = DarkHcColorTokens.colorYellow600,
    borderCriticalHovered = DarkHcColorTokens.colorRed1000,
    borderCriticalPrimary = DarkHcColorTokens.colorRed900,
    borderCriticalSubtle = DarkHcColorTokens.colorRed500,
    borderDisabled = DarkHcColorTokens.colorGray500,
    borderFocused = DarkHcColorTokens.colorYellow600,
    borderInfoSubtle = DarkHcColorTokens.colorBlue700,
    borderInteractiveHovered = DarkHcColorTokens.colorGray1100,
    borderInteractivePrimary = DarkHcColorTokens.colorGray800,
    borderInteractiveSecondary = DarkHcColorTokens.colorGray600,
    borderSuccessSubtle = DarkHcColorTokens.colorGreen500,
    gradientActionStop1 = DarkHcColorTokens.colorGreen1100,
    gradientActionStop2 = DarkHcColorTokens.colorGreen900,
    gradientActionStop3 = DarkHcColorTokens.colorGreen700,
    gradientActionStop4 = DarkHcColorTokens.colorGreen500,
    gradientInfoStop1 = DarkHcColorTokens.colorAlphaBlue500,
    gradientInfoStop2 = DarkHcColorTokens.colorAlphaBlue400,
    gradientInfoStop3 = DarkHcColorTokens.colorAlphaBlue300,
    gradientInfoStop4 = DarkHcColorTokens.colorAlphaBlue200,
    gradientInfoStop5 = DarkHcColorTokens.colorAlphaBlue100,
    gradientInfoStop6 = DarkHcColorTokens.colorTransparent,
    gradientSubtleStop1 = DarkHcColorTokens.colorAlphaYellow500,
    gradientSubtleStop2 = DarkHcColorTokens.colorAlphaYellow400,
    gradientSubtleStop3 = DarkHcColorTokens.colorAlphaYellow300,
    gradientSubtleStop4 = DarkHcColorTokens.colorAlphaYellow200,
    gradientSubtleStop5 = DarkHcColorTokens.colorAlphaYellow100,
    gradientSubtleStop6 = DarkHcColorTokens.colorTransparent,
    iconAccentPrimary = DarkHcColorTokens.colorYellow600,
    iconAccentTertiary = DarkHcColorTokens.colorYellow600,
    iconCriticalPrimary = DarkHcColorTokens.colorRed900,
    iconDisabled = DarkHcColorTokens.colorGray700,
    iconInfoPrimary = DarkHcColorTokens.colorBlue1100,
    iconOnSolidPrimary = DarkHcColorTokens.colorThemeBg,
    iconPrimary = DarkHcColorTokens.colorGray1400,
    iconPrimaryAlpha = DarkHcColorTokens.colorAlphaGray1400,
    iconQuaternary = DarkHcColorTokens.colorYellow600,
    iconQuaternaryAlpha = DarkHcColorTokens.colorAlphaGray700,
    iconSecondary = DarkHcColorTokens.colorGray900,
    iconSecondaryAlpha = DarkHcColorTokens.colorAlphaGray900,
    iconSuccessPrimary = DarkHcColorTokens.colorGreen900,
    iconTertiary = DarkHcColorTokens.colorGray800,
    iconTertiaryAlpha = DarkHcColorTokens.colorAlphaGray800,
    textActionAccent = DarkHcColorTokens.colorYellow600,
    textActionPrimary = DarkHcColorTokens.colorGray1400,
    textBadgeAccent = DarkHcColorTokens.colorGreen1100,
    textBadgeInfo = DarkHcColorTokens.colorBlue1100,
    textCriticalPrimary = DarkHcColorTokens.colorRed900,
    textDecorative1 = DarkHcColorTokens.colorLime1100,
    textDecorative2 = DarkHcColorTokens.colorCyan1100,
    textDecorative3 = DarkHcColorTokens.colorFuchsia1100,
    textDecorative4 = DarkHcColorTokens.colorPurple1100,
    textDecorative5 = DarkHcColorTokens.colorPink1100,
    textDecorative6 = DarkHcColorTokens.colorOrange1100,
    textDisabled = DarkHcColorTokens.colorGray800,
    textInfoPrimary = DarkHcColorTokens.colorBlue1100,
    textLinkExternal = DarkHcColorTokens.colorBlue1100,
    textOnSolidPrimary = DarkHcColorTokens.colorThemeBg,
    textPrimary = DarkHcColorTokens.colorGray1400,
    textSecondary = DarkHcColorTokens.colorGray900,
    textSuccessPrimary = DarkHcColorTokens.colorGreen900,
    textTertiary = DarkHcColorTokens.colorYellow600,
    isLight = false,
)
