/*
 * Copyright 2026 Belgian Secure Communications (BSC)
 * Copyright (c) 2026 Element Creations Ltd.
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial.
 * Please see LICENSE files in the repository root for full details.
 * Modified by Belgian Secure Communications for Beam application on 2026-02-09
 */

/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */

@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.LightColorTokens

/**
 * Semantic colors for the light Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsLight = SemanticColors(
    bgAccentHovered = LightColorTokens.colorYellow600,
    bgAccentPressed = LightColorTokens.colorYellow1000,
    bgAccentRest = LightColorTokens.colorYellow600,
    bgAccentSelected = LightColorTokens.colorAlphaGreen300,
    bgActionPrimaryDisabled = LightColorTokens.colorGray700,
    bgActionPrimaryHovered = LightColorTokens.colorPurple1100,
    bgActionPrimaryPressed = LightColorTokens.colorPurple1300,
    bgActionPrimaryRest = LightColorTokens.colorPurple1200,
    bgActionSecondaryHovered = LightColorTokens.colorAlphaGray200,
    bgActionSecondaryPressed = LightColorTokens.colorAlphaGray300,
    bgActionSecondaryRest = LightColorTokens.colorThemeBg,
    bgActionTertiaryHovered = LightColorTokens.colorGray300,
    bgActionTertiaryRest = LightColorTokens.colorThemeBg,
    bgActionTertiarySelected = LightColorTokens.colorGray400,
    bgBadgeAccent = LightColorTokens.colorAlphaGreen400,
    bgBadgeDefault = LightColorTokens.colorAlphaGray400,
    bgBadgeInfo = LightColorTokens.colorAlphaBlue400,
    bgCanvasDefault = LightColorTokens.colorThemeBg,
    bgCanvasDefaultLevel1 = LightColorTokens.colorThemeBg,
    bgCanvasDisabled = LightColorTokens.colorGray200,
    bgCriticalHovered = LightColorTokens.colorRed1000,
    bgCriticalPrimary = LightColorTokens.colorRed900,
    bgCriticalSubtle = LightColorTokens.colorRed200,
    bgCriticalSubtleHovered = LightColorTokens.colorRed300,
    bgDecorative1 = LightColorTokens.colorLime300,
    bgDecorative2 = LightColorTokens.colorCyan300,
    bgDecorative3 = LightColorTokens.colorFuchsia300,
    bgDecorative4 = LightColorTokens.colorPurple300,
    bgDecorative5 = LightColorTokens.colorPink300,
    bgDecorative6 = LightColorTokens.colorOrange300,
    bgInfoSubtle = LightColorTokens.colorBlue200,
    bgSubtlePrimary = LightColorTokens.colorGray400,
    bgSubtleSecondary = LightColorTokens.colorGray200,
    bgSubtleSecondaryLevel0 = LightColorTokens.colorGray300,
    bgSubtleTertiary = LightColorTokens.colorYellow200,
    bgSuccessSubtle = LightColorTokens.colorGreen200,
    borderAccentSubtle = LightColorTokens.colorYellow600,
    borderCriticalHovered = LightColorTokens.colorRed1000,
    borderCriticalPrimary = LightColorTokens.colorRed900,
    borderCriticalSubtle = LightColorTokens.colorRed500,
    borderDisabled = LightColorTokens.colorGray500,
    borderFocused = LightColorTokens.colorYellow600,
    borderInfoSubtle = LightColorTokens.colorBlue700,
    borderInteractiveHovered = LightColorTokens.colorGray1100,
    borderInteractivePrimary = LightColorTokens.colorGray800,
    borderInteractiveSecondary = LightColorTokens.colorGray600,
    borderSuccessSubtle = LightColorTokens.colorGreen500,
    gradientActionStop1 = LightColorTokens.colorYellow600,
    gradientActionStop2 = LightColorTokens.colorYellow800,
    gradientActionStop3 = LightColorTokens.colorYellow900,
    gradientActionStop4 = LightColorTokens.colorYellow1000,
    gradientInfoStop1 = LightColorTokens.colorAlphaBlue500,
    gradientInfoStop2 = LightColorTokens.colorAlphaBlue400,
    gradientInfoStop3 = LightColorTokens.colorAlphaBlue300,
    gradientInfoStop4 = LightColorTokens.colorAlphaBlue200,
    gradientInfoStop5 = LightColorTokens.colorAlphaBlue100,
    gradientInfoStop6 = LightColorTokens.colorTransparent,
    gradientSubtleStop1 = LightColorTokens.colorAlphaYellow500,
    gradientSubtleStop2 = LightColorTokens.colorAlphaYellow400,
    gradientSubtleStop3 = LightColorTokens.colorAlphaYellow300,
    gradientSubtleStop4 = LightColorTokens.colorAlphaYellow200,
    gradientSubtleStop5 = LightColorTokens.colorAlphaYellow100,
    gradientSubtleStop6 = LightColorTokens.colorTransparent,
    iconAccentPrimary = LightColorTokens.colorYellow600,
    iconAccentTertiary = LightColorTokens.colorYellow600,
    iconCriticalPrimary = LightColorTokens.colorRed900,
    iconDisabled = LightColorTokens.colorGray700,
    iconInfoPrimary = LightColorTokens.colorBlue1100,
    iconOnSolidPrimary = LightColorTokens.colorThemeBg,
    iconPrimary = LightColorTokens.colorGray1400,
    iconPrimaryAlpha = LightColorTokens.colorAlphaGray1400,
    iconQuaternary = LightColorTokens.colorYellow600,
    iconQuaternaryAlpha = LightColorTokens.colorAlphaGray700,
    iconSecondary = LightColorTokens.colorGray900,
    iconSecondaryAlpha = LightColorTokens.colorAlphaGray900,
    iconSuccessPrimary = LightColorTokens.colorGreen900,
    iconTertiary = LightColorTokens.colorGray800,
    iconTertiaryAlpha = LightColorTokens.colorAlphaGray800,
    textActionAccent = LightColorTokens.colorYellow600,
    textActionPrimary = LightColorTokens.colorGray1400,
    textBadgeAccent = LightColorTokens.colorGreen1100,
    textBadgeInfo = LightColorTokens.colorBlue1100,
    textCriticalPrimary = LightColorTokens.colorRed900,
    textDecorative1 = LightColorTokens.colorLime1100,
    textDecorative2 = LightColorTokens.colorCyan1100,
    textDecorative3 = LightColorTokens.colorFuchsia1100,
    textDecorative4 = LightColorTokens.colorPurple1100,
    textDecorative5 = LightColorTokens.colorPink1100,
    textDecorative6 = LightColorTokens.colorOrange1100,
    textDisabled = LightColorTokens.colorGray800,
    textInfoPrimary = LightColorTokens.colorBlue1100,
    textLinkExternal = LightColorTokens.colorBlue1100,
    textOnSolidPrimary = LightColorTokens.colorThemeBg,
    textPrimary = LightColorTokens.colorGray1400,
    textSecondary = LightColorTokens.colorGray900,
    textSuccessPrimary = LightColorTokens.colorGreen900,
    textTertiary = LightColorTokens.colorYellow600,
    isLight = true,
)
