/*
 * Copyright 2026 Belgian Secure Communications (BSC)
 * Copyright (c) 2026 Element Creations Ltd.
 *
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial.
 * Please see LICENSE files in the repository root for full details.
 * Modified by Belgian Secure Communications for Beam application on 2026-03-25
 */

/**
 * !!! WARNING !!!
 * 
 * THIS IS AN AUTOGENERATED FILE.
 * DO NOT EDIT MANUALLY.
 */

@file:Suppress("all")
package io.element.android.compound.tokens.generated

import io.element.android.compound.annotations.CoreColorToken
import io.element.android.compound.tokens.generated.internal.DarkColorTokens

/**
 * Semantic colors for the dark Compound theme.
 */
@OptIn(CoreColorToken::class)
val compoundColorsDark = SemanticColors(
    bgAccentHovered = DarkColorTokens.colorYellow600,
    bgAccentPressed = DarkColorTokens.colorYellow1000,
    bgAccentRest = DarkColorTokens.colorYellow600,
    bgAccentSelected = DarkColorTokens.colorAlphaGreen300,
    bgActionPrimaryDisabled = DarkColorTokens.colorGray700,
    bgActionPrimaryHovered = DarkColorTokens.colorYellow500,
    bgActionPrimaryPressed = DarkColorTokens.colorYellow1000,
    bgActionPrimaryRest = DarkColorTokens.colorYellow800,
    bgActionSecondaryHovered = DarkColorTokens.colorAlphaGray200,
    bgActionSecondaryPressed = DarkColorTokens.colorAlphaGray300,
    bgActionSecondaryRest = DarkColorTokens.colorThemeBg,
    bgActionTertiaryHovered = DarkColorTokens.colorGray300,
    bgActionTertiaryRest = DarkColorTokens.colorThemeBg,
    bgActionTertiarySelected = DarkColorTokens.colorGray400,
    bgBadgeAccent = DarkColorTokens.colorAlphaGreen500,
    bgBadgeDefault = DarkColorTokens.colorAlphaGray500,
    bgBadgeInfo = DarkColorTokens.colorAlphaBlue500,
    bgCanvasDefault = DarkColorTokens.colorThemeBg,
    bgCanvasDefaultLevel1 = DarkColorTokens.colorGray300,
    bgCanvasDisabled = DarkColorTokens.colorGray200,
    bgCriticalHovered = DarkColorTokens.colorRed1000,
    bgCriticalPrimary = DarkColorTokens.colorRed900,
    bgCriticalSubtle = DarkColorTokens.colorRed200,
    bgCriticalSubtleHovered = DarkColorTokens.colorRed300,
    bgDecorative1 = DarkColorTokens.colorLime300,
    bgDecorative2 = DarkColorTokens.colorCyan300,
    bgDecorative3 = DarkColorTokens.colorFuchsia300,
    bgDecorative4 = DarkColorTokens.colorPurple300,
    bgDecorative5 = DarkColorTokens.colorPink300,
    bgDecorative6 = DarkColorTokens.colorOrange300,
    bgInfoSubtle = DarkColorTokens.colorBlue200,
    bgMentionUser = DarkColorTokens.colorAlphaYellow400,
    bgSubtlePrimary = DarkColorTokens.colorGray500,
    bgSubtleSecondary = DarkColorTokens.colorGray300,
    bgSubtleSecondaryLevel0 = DarkColorTokens.colorThemeBg,
    bgSubtleTertiary = DarkColorTokens.colorYellow1400,
    bgSuccessSubtle = DarkColorTokens.colorGreen200,
    borderAccentSubtle = DarkColorTokens.colorYellow600,
    borderCriticalHovered = DarkColorTokens.colorRed1000,
    borderCriticalPrimary = DarkColorTokens.colorRed900,
    borderCriticalSubtle = DarkColorTokens.colorRed500,
    borderDisabled = DarkColorTokens.colorGray500,
    borderFocused = DarkColorTokens.colorYellow600,
    borderInfoSubtle = DarkColorTokens.colorBlue700,
    borderInteractiveHovered = DarkColorTokens.colorGray1100,
    borderInteractivePrimary = DarkColorTokens.colorGray800,
    borderInteractiveSecondary = DarkColorTokens.colorGray600,
    borderSuccessSubtle = DarkColorTokens.colorGreen500,
    gradientActionStop1 = DarkColorTokens.colorYellow600,
    gradientActionStop2 = DarkColorTokens.colorYellow800,
    gradientActionStop3 = DarkColorTokens.colorYellow900,
    gradientActionStop4 = DarkColorTokens.colorYellow1000,
    gradientCriticalStop1 = DarkColorTokens.colorRed200,
    gradientCriticalStop2 = DarkColorTokens.colorThemeBg,
    gradientInfoStop1 = DarkColorTokens.colorBlue200,
    gradientInfoStop2 = DarkColorTokens.colorThemeBg,
    gradientSubtleStop1 = DarkColorTokens.colorAlphaYellow500,
    gradientSubtleStop2 = DarkColorTokens.colorAlphaYellow400,
    gradientSubtleStop3 = DarkColorTokens.colorAlphaYellow300,
    gradientSubtleStop4 = DarkColorTokens.colorAlphaYellow200,
    gradientSubtleStop5 = DarkColorTokens.colorAlphaYellow100,
    gradientSubtleStop6 = DarkColorTokens.colorTransparent,
    iconAccentPrimary = DarkColorTokens.colorYellow600,
    iconAccentTertiary = DarkColorTokens.colorYellow600,
    iconCriticalPrimary = DarkColorTokens.colorRed900,
    iconDisabled = DarkColorTokens.colorGray700,
    iconInfoPrimary = DarkColorTokens.colorBlue1100,
    iconOnSolidPrimary = DarkColorTokens.colorThemeBg,
    iconPrimary = DarkColorTokens.colorGray1400,
    iconPrimaryAlpha = DarkColorTokens.colorAlphaGray1400,
    iconQuaternary = DarkColorTokens.colorYellow600,
    iconQuaternaryAlpha = DarkColorTokens.colorAlphaGray700,
    iconSecondary = DarkColorTokens.colorGray900,
    iconSecondaryAlpha = DarkColorTokens.colorAlphaGray900,
    iconSuccessPrimary = DarkColorTokens.colorGreen900,
    iconTertiary = DarkColorTokens.colorGray800,
    iconTertiaryAlpha = DarkColorTokens.colorAlphaGray800,
    textActionAccent = DarkColorTokens.colorYellow600,
    textActionPrimary = DarkColorTokens.colorGray1400,
    textBadgeAccent = DarkColorTokens.colorGreen1100,
    textBadgeInfo = DarkColorTokens.colorBlue1100,
    textCriticalPrimary = DarkColorTokens.colorRed900,
    textDecorative1 = DarkColorTokens.colorLime1100,
    textDecorative2 = DarkColorTokens.colorCyan1100,
    textDecorative3 = DarkColorTokens.colorFuchsia1100,
    textDecorative4 = DarkColorTokens.colorPurple1100,
    textDecorative5 = DarkColorTokens.colorPink1100,
    textDecorative6 = DarkColorTokens.colorOrange1100,
    textDisabled = DarkColorTokens.colorGray800,
    textInfoPrimary = DarkColorTokens.colorBlue1100,
    textLinkExternal = DarkColorTokens.colorBlue1100,
    textMentionUser = DarkColorTokens.colorYellow600,
    textOnSolidPrimary = DarkColorTokens.colorThemeBg,
    textPrimary = DarkColorTokens.colorGray1400,
    textSecondary = DarkColorTokens.colorGray1100,
    textSuccessPrimary = DarkColorTokens.colorGreen900,
    textTertiary = DarkColorTokens.colorYellow600,
    isLight = false,
)
